#!/usr/bin/env node
/**
 * build-feed.js — the Meta Commerce Manager product feed.
 *
 * Writes public/feed.xml, which ships with the site and is served at
 * {SITE_URL}/feed.xml. Runs before `next build`, so the feed a deploy serves is
 * always the catalog that deploy renders — a feed generated by hand drifts the
 * first time prices change, and Meta keeps selling the old price until someone
 * notices.
 *
 * Format is RSS 2.0 with Google's `g:` namespace, which is what Meta's
 * scheduled-fetch importer reads.
 *
 * Two decisions worth knowing about
 * ---------------------------------
 * `g:id` is `GLD_<id>`, not the bare id. The prefix has to match the
 * `content_ids` the Meta Pixel fires on this site or nothing attributes, and it
 * keeps this campaign catalog from colliding with the main alta.ge one, which
 * uses the same product codes. It changed from `TLV_` with the campaign: this
 * is a separate catalog for a separate branch, and reusing the Telavi ids would
 * merge two campaigns' attribution into one.
 *
 * `g:item_group_id` groups colour and capacity variants — see
 * `scripts/lib/variants.mjs`. Without it a dynamic ad carousel shows the same
 * handset in four colours and calls it four products.
 *
 * Validation
 * ----------
 * Every run validates what it wrote and prints a report, also saved to
 * reports/feed-report.md. A missing *required* field exits non-zero, because a
 * feed Meta will reject item-by-item is worse than no new feed at all.
 * Everything else — a dead image, an inverted price, a duplicate id — is
 * reported and does not block the deploy.
 *
 * Usage
 * -----
 *   npm run feed                      write, validate, check every image URL
 *   npm run feed -- --skip-image-check   what the build runs
 *   npm run feed -- --domain https://…   override the site URL
 */

import fs from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

import { extractColour, extractSize, feedGroupKey } from "./lib/variants.mjs";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const OUT_FILE = path.join(ROOT, "public", "feed.xml");
const REPORT_FILE = path.join(ROOT, "reports", "feed-report.md");
const GPC_FILE = path.join(ROOT, "data", "gpc-mapping.json");

/**
 * Where the site is served. Every `g:link` and `g:image_link` has to be
 * absolute — Meta fetches the feed from its own servers, so a relative path
 * resolves against nothing.
 */
const DEFAULT_DOMAIN = "https://alta-gldani-cashback.vercel.app";

const UTM = {
  source: "Facebookads",
  campaign: "gldani_september",
};

/** Meta truncates past these; better to cut deliberately than be cut. */
const MAX_TITLE = 150;
const MAX_DESCRIPTION = 5000;
/** Google's spec allows ten beyond the main image. */
const MAX_ADDITIONAL_IMAGES = 10;

const CURRENCY = "GEL";

/** Without one of these an item is rejected, so the build stops. */
const REQUIRED = [
  "g:id",
  "g:title",
  "g:description",
  "g:link",
  "g:image_link",
  "g:availability",
  "g:condition",
  "g:price",
  "g:brand",
];

/* ------------------------------------------------------------------ */
/* Arguments                                                           */
/* ------------------------------------------------------------------ */

function parseArgs(argv) {
  const flags = { checkImages: true, domain: null };
  for (let i = 0; i < argv.length; i += 1) {
    const arg = argv[i];
    if (arg === "--skip-image-check") flags.checkImages = false;
    else if (arg === "--domain") flags.domain = String(argv[++i] ?? "").trim();
    else if (arg.startsWith("--")) throw new Error(`უცნობი დროშა: ${arg}`);
  }
  return flags;
}

const readJson = async (file, fallback = null) => {
  try {
    return JSON.parse(await fs.readFile(file, "utf8"));
  } catch {
    return fallback;
  }
};

/* ------------------------------------------------------------------ */
/* Text                                                                */
/* ------------------------------------------------------------------ */

/**
 * XML 1.0 forbids most control characters outright — not escaped, forbidden.
 * One in a scraped description makes the whole feed unparseable, and Meta
 * reports that as "could not read your feed" with no clue which item did it.
 */
const CONTROL = /[\u0000-\u0008\u000B\u000C\u000E-\u001F\u007F]/g;

const escapeXml = (value) =>
  String(value ?? "")
    .replace(CONTROL, "")
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&apos;");

/** HTML out, entities decoded, whitespace collapsed. */
function plainText(html) {
  return String(html ?? "")
    .replace(/<(script|style)[^>]*>[\s\S]*?<\/\1>/gi, " ")
    .replace(/<br\s*\/?>/gi, " ")
    .replace(/<\/(p|div|li|tr|h[1-6])>/gi, " ")
    .replace(/<[^>]+>/g, " ")
    .replace(/&nbsp;/gi, " ")
    .replace(/&amp;/gi, "&")
    .replace(/&lt;/gi, "<")
    .replace(/&gt;/gi, ">")
    .replace(/&quot;/gi, '"')
    .replace(/&#(\d+);/g, (_, code) => String.fromCodePoint(Number(code)))
    .replace(/\s+/g, " ")
    .trim();
}

/** Cuts at a word boundary when there is one nearby, so nothing ends mid-word. */
function truncate(text, limit) {
  if (text.length <= limit) return text;
  const cut = text.slice(0, limit);
  const space = cut.lastIndexOf(" ");
  return (space > limit * 0.8 ? cut.slice(0, space) : cut).trim();
}

/* ------------------------------------------------------------------ */
/* Field builders                                                      */
/* ------------------------------------------------------------------ */

/**
 * A description built from what is known, for the products that have none.
 *
 * All but one product in this catalog arrives without a description, and Meta
 * rejects an item with an empty one outright — so this is not a rare fallback,
 * it is what almost every item ships with. It has to read like a sentence
 * somebody wrote: brand and product kind, then the attributes a shopper would
 * actually ask about, then the offer.
 */
/**
 * Spec keys that do not belong in ad copy: the brand is already in the
 * sentence above, and a part number sells nothing.
 */
const DESCRIPTION_SKIP_SPECS = new Set([
  "ბრენდი",
  "მოდელი",
  "მოდელი/PN",
  "სერია",
  "შტრიხკოდი",
]);

function generateDescription(product, { subcategoryLabel, discount }) {
  const parts = [];

  // The title leads, then what kind of thing it is and who made it. Written
  // this way round so the brand is not repeated: nearly every title in this
  // catalog already begins with it.
  const context = [subcategoryLabel, product.brand ? `ბრენდი: ${product.brand}` : ""]
    .filter(Boolean)
    .join(", ");
  parts.push(context ? `${product.title} — ${context}.` : `${product.title}.`);

  const specs = Object.entries(product.specs ?? {})
    .filter(([key, value]) => key && value && !DESCRIPTION_SKIP_SPECS.has(key))
    .slice(0, 5)
    .map(([key, value]) => `${key}: ${value}`);
  if (specs.length) parts.push(`${specs.join(", ")}.`);

  parts.push(
    discount > 0
      ? `ფასდაკლება ${discount}% — ${product.promo_price}₾ ${product.old_price}₾-ის ნაცვლად. ალტა, გლდანის ფილიალი, 12–13 სექტემბერს.`
      : "ალტა, გლდანის ფილიალი, 12–13 სექტემბერს.",
  );

  return parts.join(" ");
}

/**
 * The product page, tagged so Meta traffic is identifiable in analytics.
 *
 * `utm_medium` carries the product title, URL-encoded — unusual, but it is
 * what the existing campaign reporting keys off, so it stays.
 */
function productLink(product, domain) {
  const params = new URLSearchParams({
    utm_source: UTM.source,
    utm_medium: product.title,
    utm_campaign: UTM.campaign,
  });
  return `${domain}/product/${encodeURIComponent(product.id)}?${params.toString()}`;
}

/** Absolute, always. A relative path in a feed resolves against Meta, not us. */
const absolute = (url, domain) => {
  const value = String(url ?? "").trim();
  if (!value) return null;
  if (/^https?:\/\//i.test(value)) return value;
  if (value.startsWith("//")) return `https:${value}`;
  return `${domain}${value.startsWith("/") ? "" : "/"}${value}`;
};

const discountBucket = (pct) => {
  if (pct >= 30) return "30+";
  if (pct >= 20) return "20-30";
  if (pct >= 10) return "10-20";
  // Not in the original three buckets, but a fifth of this catalog sits here
  // and every item needs a label or the segment silently excludes them.
  return "under_10";
};

const priceBucket = (price) => {
  if (price >= 3000) return "3000_plus";
  if (price >= 1000) return "1000_3000";
  if (price >= 300) return "300_1000";
  return "under_300";
};

/** Whole lari where the price is whole, which is all of them today. */
const money = (value) =>
  `${Number.isInteger(value) ? value : Number(value).toFixed(2)} ${CURRENCY}`;

/**
 * The brand, or the first word of the title.
 *
 * `g:brand` is required and an item without one is dropped, so a guess beats a
 * blank — and these titles are written "<Brand> <model>", which makes the first
 * word right far more often than not. Rejected when it looks like a part
 * number rather than a name.
 */
function brandFor(product) {
  const brand = String(product.brand ?? "").trim();
  if (brand && brand !== "სხვა") return brand;
  const first = String(product.title ?? "").trim().split(/\s+/)[0] ?? "";
  if (/^[\p{L}][\p{L}'&-]{1,}$/u.test(first)) return first;
  return brand || null;
}

/* ------------------------------------------------------------------ */
/* Item                                                                */
/* ------------------------------------------------------------------ */

function buildItem(product, context) {
  const { domain, labels, groups, gpc, groupSizes } = context;

  const category = labels.get(product.category);
  const categoryLabel = category?.label ?? product.category;
  const subcategoryLabel =
    category?.subcategories.get(product.subcategory) ?? product.subcategory;
  const productType = `${categoryLabel} > ${subcategoryLabel}`;

  const discount =
    product.old_price > product.promo_price
      ? Math.round(
          ((product.old_price - product.promo_price) / product.old_price) * 100,
        )
      : 0;

  const described = plainText(product.description);
  const description = truncate(
    described ||
      generateDescription(product, { subcategoryLabel, discount }),
    MAX_DESCRIPTION,
  );

  const image = absolute(product.image, domain);
  const gallery = (product.gallery ?? [])
    .map((src) => absolute(src, domain))
    .filter((src) => src && src !== image)
    .slice(0, MAX_ADDITIONAL_IMAGES);

  /** @type {Array<[string, string | null]>} */
  const fields = [
    ["g:id", `GLD_${product.id}`],
    ["g:title", truncate(product.title, MAX_TITLE)],
    ["g:description", description],
    ["g:link", productLink(product, domain)],
    ["g:image_link", image],
    ["g:availability", product.stock ? "in stock" : "out of stock"],
    ["g:condition", "new"],
    ["g:price", money(product.old_price)],
    ["g:sale_price", money(product.promo_price)],
    ["g:brand", brandFor(product)],
    ["g:product_type", productType],
    ["g:google_product_category", gpc(productType, subcategoryLabel, categoryLabel)],
  ];

  /*
   * Variant attributes are only emitted for products that actually have a
   * sibling. A lone item carrying an item_group_id of its own tells Meta it is
   * one of a set it will then never find, and a `g:color` on a product with no
   * colour variants adds a filter dimension with one value in it.
   */
  const groupKey = feedGroupKey(product);
  if ((groupSizes.get(groupKey) ?? 0) > 1) {
    fields.push(["g:item_group_id", groups.get(groupKey)]);
    fields.push(["g:color", extractColour(product.title)]);
    fields.push(["g:size", extractSize(product.title)]);
  }

  fields.push(["g:custom_label_0", discountBucket(discount)]);
  fields.push(["g:custom_label_1", priceBucket(product.promo_price)]);
  fields.push(["g:custom_label_2", context.sourceGroup(product.category)]);

  for (const src of gallery) fields.push(["g:additional_image_link", src]);

  return { product, fields: fields.filter(([, value]) => value != null) };
}

const renderItem = (item) =>
  [
    "    <item>",
    ...item.fields.map(
      ([name, value]) => `      <${name}>${escapeXml(value)}</${name}>`,
    ),
    "    </item>",
  ].join("\n");

/* ------------------------------------------------------------------ */
/* Validation                                                          */
/* ------------------------------------------------------------------ */

/**
 * HEAD every distinct image, a few at a time.
 *
 * Off during the build: 300-odd requests to a third-party CDN would add most
 * of a minute to every deploy and hand it a way to fail that has nothing to do
 * with the code. Run `npm run feed` by hand to check them.
 */
async function checkImages(urls, concurrency = 8) {
  const queue = [...urls];
  /** @type {Array<{ url: string, status: number | string }>} */
  const broken = [];
  let unreachable = 0;

  const worker = async () => {
    for (;;) {
      const url = queue.shift();
      if (!url) return;
      try {
        let res = await fetch(url, { method: "HEAD", redirect: "follow" });
        // Some CDNs answer HEAD with 405 but serve the bytes happily.
        if (res.status === 405 || res.status === 501)
          res = await fetch(url, { method: "GET", redirect: "follow" });
        if (!res.ok) broken.push({ url, status: res.status });
      } catch (error) {
        // A network failure here is this environment's, not the feed's.
        unreachable += 1;
        void error;
      }
    }
  };

  await Promise.all(
    Array.from({ length: Math.min(concurrency, queue.length) }, worker),
  );

  /*
   * Distinguish "these images are gone" from "we cannot see this host".
   *
   * A CDN that answers every request with the same status is telling you about
   * the client, not the pictures — an egress allowlist, a hotlink guard, a
   * blanket rate limit. Reporting that as 1374 broken images buries the signal
   * and would train whoever reads this report to ignore it. Anything above 90%
   * of a host's URLs failing identically is reported once, as a host problem.
   */
  const byHostStatus = new Map();
  const perHost = new Map();
  for (const url of urls) {
    const host = safeHost(url);
    perHost.set(host, (perHost.get(host) ?? 0) + 1);
  }
  for (const entry of broken) {
    const key = `${safeHost(entry.url)}|${entry.status}`;
    if (!byHostStatus.has(key)) byHostStatus.set(key, []);
    byHostStatus.get(key).push(entry);
  }

  const blanket = [];
  const individual = [];
  for (const [key, entries] of byHostStatus) {
    const [host, status] = key.split("|");
    if (entries.length >= (perHost.get(host) ?? 0) * 0.9 && entries.length > 5)
      blanket.push({ host, status, count: entries.length });
    else individual.push(...entries);
  }

  return { broken: individual, blanket, unreachable, checked: urls.length };
}

const safeHost = (url) => {
  try {
    return new URL(url).host;
  } catch {
    return "(invalid url)";
  }
};

function validate(items) {
  const missing = [];
  const inverted = [];
  const duplicates = [];

  const seen = new Map();
  for (const item of items) {
    const byName = new Map(item.fields);
    const absent = REQUIRED.filter((name) => {
      const value = byName.get(name);
      return value == null || String(value).trim() === "";
    });
    if (absent.length) missing.push({ item, absent });

    const id = byName.get("g:id");
    seen.set(id, (seen.get(id) ?? 0) + 1);

    const price = Number(String(byName.get("g:price")).replace(/[^\d.]/g, ""));
    const sale = Number(
      String(byName.get("g:sale_price") ?? "").replace(/[^\d.]/g, ""),
    );
    if (byName.has("g:sale_price") && !(sale < price))
      inverted.push({ item, price, sale });
  }

  for (const [id, count] of seen) if (count > 1) duplicates.push({ id, count });

  return { missing, inverted, duplicates };
}

/* ------------------------------------------------------------------ */
/* Main                                                                */
/* ------------------------------------------------------------------ */

async function main() {
  const flags = parseArgs(process.argv.slice(2));
  const domain = (
    flags.domain ||
    process.env.SITE_URL ||
    process.env.NEXT_PUBLIC_SITE_URL ||
    DEFAULT_DOMAIN
  ).replace(/\/+$/, "");

  const products = await readJson(path.join(ROOT, "data", "products.json"), []);
  const categories = await readJson(path.join(ROOT, "data", "categories.json"), []);
  const categoryMap = await readJson(
    path.join(ROOT, "data", "csv-category-map.json"),
    {},
  );

  if (!products.length) throw new Error("data/products.json ცარიელია");

  const labels = new Map(
    categories.map((c) => [
      c.id,
      {
        label: c.label,
        subcategories: new Map(c.subcategories.map((s) => [s.id, s.label])),
      },
    ]),
  );

  // custom_label_2 is the sheet the product came from in the commercial team's
  // workbook — "TV & Gaming", "თეთრი ტექნიკა". That is the vocabulary they plan
  // campaigns in, so it is the one worth segmenting on.
  const slugToGroup = new Map(
    Object.entries(categoryMap.groups ?? {}).map(([name, meta]) => [
      meta.slug,
      name,
    ]),
  );
  const sourceGroup = (categorySlug) =>
    slugToGroup.get(categorySlug) ?? categorySlug;

  /* --- Google product category ---------------------------------- */

  const gpcMap = await readJson(GPC_FILE, null);
  const unmappedTypes = new Set();
  const gpc = (productType, subcategoryLabel, categoryLabel) => {
    if (!gpcMap) {
      unmappedTypes.add(productType);
      return null;
    }
    const table = gpcMap.categories ?? gpcMap;
    for (const key of [productType, subcategoryLabel, categoryLabel]) {
      const value = table[key];
      if (value != null && String(value).trim() !== "") return String(value);
    }
    // Omitted rather than guessed: a wrong taxonomy id is worse than none,
    // because Meta will happily optimise against the wrong vertical.
    unmappedTypes.add(productType);
    return null;
  };

  /* --- variant groups ------------------------------------------- */

  const groupSizes = new Map();
  for (const product of products) {
    const key = feedGroupKey(product);
    groupSizes.set(key, (groupSizes.get(key) ?? 0) + 1);
  }
  // A stable, readable id per group. Derived from the key so it survives a
  // rebuild — Meta treats a changed item_group_id as a different set.
  const groups = new Map(
    [...groupSizes.keys()].map((key) => [
      key,
      `TLVG_${key.replace(/[^\p{L}\p{N}]+/gu, "_").replace(/^_+|_+$/g, "").slice(0, 60)}`,
    ]),
  );

  /* --- build ----------------------------------------------------- */

  const context = { domain, labels, groups, groupSizes, gpc, sourceGroup };
  const items = products.map((product) => buildItem(product, context));

  const now = new Date().toUTCString();
  const xml = [
    '<?xml version="1.0" encoding="UTF-8"?>',
    '<rss version="2.0" xmlns:g="http://base.google.com/ns/1.0">',
    "  <channel>",
    `    <title>${escapeXml("ალტა — დიდი ფასდაკლება გლდანში")}</title>`,
    `    <link>${escapeXml(domain)}</link>`,
    `    <description>${escapeXml(
      "ალტას გლდანის ფილიალის სააქციო კატალოგი Meta Commerce Manager-ისთვის.",
    )}</description>`,
    `    <lastBuildDate>${now}</lastBuildDate>`,
    ...items.map(renderItem),
    "  </channel>",
    "</rss>",
    "",
  ].join("\n");

  await fs.mkdir(path.dirname(OUT_FILE), { recursive: true });
  await fs.writeFile(OUT_FILE, xml, "utf8");

  /* --- validate -------------------------------------------------- */

  const { missing, inverted, duplicates } = validate(items);

  const imageUrls = [
    ...new Set(
      items.flatMap((item) =>
        item.fields
          .filter(([name]) => name === "g:image_link" || name === "g:additional_image_link")
          .map(([, value]) => value),
      ),
    ),
  ];
  const images = flags.checkImages
    ? await checkImages(imageUrls)
    : {
        broken: [],
        blanket: [],
        unreachable: 0,
        checked: 0,
        skipped: imageUrls.length,
      };

  const withoutDescription = items.filter((item) => {
    const product = item.product;
    return !plainText(product.description);
  }).length;
  const grouped = items.filter((item) =>
    item.fields.some(([name]) => name === "g:item_group_id"),
  ).length;
  const withGpc = items.filter((item) =>
    item.fields.some(([name]) => name === "g:google_product_category"),
  ).length;

  const bytes = Buffer.byteLength(xml, "utf8");
  const table = (rows, cols) =>
    rows.length
      ? [`| ${cols.join(" | ")} |`, `| ${cols.map(() => "---").join(" | ")} |`, ...rows, ""].join("\n")
      : "_არცერთი._\n";

  const report = `# Meta პროდუქტ-ფიდის ანგარიში

გენერირებულია: ${now}
მისამართი: ${domain}/feed.xml
ფაილი: public/feed.xml (${(bytes / 1024).toFixed(0)} KB)

| მაჩვენებელი | რაოდენობა |
| --- | --- |
| item | ${items.length} |
| ვარიანტულ ჯგუფში (item_group_id) | ${grouped} |
| ვარიანტული ჯგუფი სულ | ${[...groupSizes.values()].filter((n) => n > 1).length} |
| აღწერა დაგენერირებული (scrape-ს არ ჰქონდა) | ${withoutDescription} |
| google_product_category მინიჭებული | ${withGpc} |
| სავალდებულო ველი აკლია | ${missing.length} |
| sale_price >= price | ${inverted.length} |
| გამეორებული g:id | ${duplicates.length} |
| ფოტოს URL შემოწმდა | ${flags.checkImages ? images.checked : `0 (გამოტოვებული: ${images.skipped})`} |
| ფოტო არა-200 პასუხით | ${images.broken.length} |
| მთლიანად დაბლოკილი ჰოსტი | ${(images.blanket ?? []).length} |
| ფოტო მიუწვდომელი (ქსელი) | ${images.unreachable} |

## სავალდებულო ველი აკლია (${missing.length})

${table(
  missing.map((m) => `| ${m.item.product.id} | ${m.item.product.title.replace(/\|/g, "/")} | ${m.absent.join(", ")} |`),
  ["კოდი", "დასახელება", "აკლია"],
)}
## sale_price არ არის price-ზე ნაკლები (${inverted.length})

ასეთ item-ზე Meta ფასდაკლების ბეჯს არ დახატავს.

${table(
  inverted.map((i) => `| ${i.item.product.id} | ${i.price} | ${i.sale} |`),
  ["კოდი", "price", "sale_price"],
)}
## გამეორებული g:id (${duplicates.length})

${table(
  duplicates.map((d) => `| ${d.id} | ${d.count} |`),
  ["g:id", "რაოდენობა"],
)}
## ფოტო არა-200 პასუხით (${images.broken.length})

${table(
  images.broken.slice(0, 50).map((b) => `| ${b.status} | ${b.url} |`),
  ["სტატუსი", "URL"],
)}
## მთლიანად დაბლოკილი ჰოსტი (${(images.blanket ?? []).length})

როცა ერთი ჰოსტის თითქმის ყველა URL ერთი და იმავე კოდით ბრუნდება, ეს ფოტოებზე
კი არა, კლიენტზეა ნათქვამი — egress-ის allowlist, hotlink-დაცვა ან rate limit.
ცალკეულ ფოტოებად ჩამოთვლა აქ სიგნალს კლავს, ამიტომ ერთ სტრიქონად ჩანს.
შესამოწმებლად გახსენით რომელიმე URL ბრაუზერში, ან გაუშვით \`npm run feed\`
იმ მანქანიდან, რომელსაც ჰოსტამდე წვდომა აქვს.

${table(
  (images.blanket ?? []).map((b) => `| ${b.host} | ${b.status} | ${b.count} |`),
  ["ჰოსტი", "სტატუსი", "URL"],
)}
## google_product_category-ის გარეშე (${unmappedTypes.size} კატეგორია)

${
  gpcMap
    ? "ამ კატეგორიებს `data/gpc-mapping.json`-ში შესატყვისი არ აქვთ, ამიტომ ველი გამოტოვებულია — არასწორი ტაქსონომიის ID უარესია, ვიდრე არარსებული."
    : "`data/gpc-mapping.json` არ არსებობს, ამიტომ ველი არცერთ item-ზე არ დაწერილა."
}

${
  unmappedTypes.size
    ? [...unmappedTypes].sort().map((t) => `- \`${t}\``).join("\n") + "\n"
    : "_არცერთი._\n"
}`;

  await fs.mkdir(path.dirname(REPORT_FILE), { recursive: true });
  await fs.writeFile(REPORT_FILE, report, "utf8");

  console.log(
    `public/feed.xml — ${items.length} item, ${(bytes / 1024).toFixed(0)} KB, ${domain}/feed.xml\n` +
      `ვარიანტული ჯგუფი: ${[...groupSizes.values()].filter((n) => n > 1).length} ` +
      `(${grouped} item), აღწერა დაგენერირებული: ${withoutDescription}, ` +
      `google_product_category: ${withGpc}/${items.length}\n` +
      `სავალდებულო ველი აკლია: ${missing.length}, sale_price >= price: ${inverted.length}, ` +
      `გამეორებული id: ${duplicates.length}, ` +
      (flags.checkImages
        ? `ფოტო: ${images.broken.length} შეცდომით, ` +
          `${(images.blanket ?? []).length} დაბლოკილი ჰოსტი, ` +
          `${images.unreachable} მიუწვდომელი (${images.checked} შემოწმდა)`
        : `ფოტოს შემოწმება გამოტოვებულია (${images.skipped} URL)`) +
      `\nანგარიში: reports/feed-report.md`,
  );

  if (missing.length) {
    console.error(
      `\n${missing.length} item-ს სავალდებულო ველი აკლია — Meta მათ უარყოფს. ` +
        `დეტალები: reports/feed-report.md`,
    );
    process.exit(1);
  }
}

main().catch((error) => {
  console.error(String(error.stack ?? error));
  process.exit(1);
});
